version: "3.8"

services:

  webserver:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - login_api
    networks:
      - dev_network

  login_api:
    build:
      context: ./APIS
    ports:
      - "3000:3000"  
    volumes:
      - ./APIS/login:/usr/loginAPI
    networks:
      - dev_network

  db_dev:
    image: postgres:latest
    container_name: user_db_dev
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 1GB
        reservations:
          cpus: "0.1"
          memory: 1GB
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user   # Nombre del usuario
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=login_db # Nombre de la base de datos
    volumes:
      - ./login_data_dev:/var/lib/postgresql/data
    networks:
      - dev_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "carlos@guerrero.com"
      PGADMIN_DEFAULT_PASSWORD: "12345"
    ports:
      - "8888:80"
    depends_on:
      - db_dev
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge
